package views;

import controllers.PMController;
import entities.Admin;
import entities.Buku;
import entities.Customer;
import entities.User;
import javax.swing.JOptionPane;

public class MainFrame extends javax.swing.JFrame {

    private PMController controller;
    private User currentUser;

    public MainFrame(PMController controller, User user) {
        this.controller = controller;
        initComponents();
        connected();
        this.currentUser = user;
    }

    void connected() {
        addMessaage("Sudah terhubung dengan controller");
    }

    void addMessaage(String message) {
        lblStatus.setText("Status : " + message);
    }

    public PMController getController() {
        return controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        btnAllProduct = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Manager Apps");

        btnRegister.setText("Book Registration");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBuku(evt);
            }
        });

        btnAllProduct.setText("Get All Book");
        btnAllProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllProductActionPerformed(evt);
            }
        });

        btnFind.setText("Find A Book");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrder(evt);
            }
        });

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        lblStatus.setText("Status : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAllProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnAllProduct)
                    .addComponent(btnFind)
                    .addComponent(btnOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        btnRegister.getAccessibleContext().setAccessibleName("Book Registration");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllProductActionPerformed
        // TODO add your handling code here:
        display.append(controller.getAllBuku().toString());
        addMessaage("Semua product tampil di display");
    }//GEN-LAST:event_btnAllProductActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog("Masukkan ID product?");
        Buku p = controller.findProductById(id);
        try {
            if (p == null) {
                JOptionPane.showMessageDialog(this, "tidak ketemu");
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        display.append(controller.findProductById(id).toString());
        addMessaage("Product dengan id " + id + " ditemukan");
    }//GEN-LAST:event_btnFindActionPerformed

    private void RegisterBuku(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBuku
        // TODO add your handling code here:
        if (currentUser instanceof Admin) {
            RegisterDialog dialog = new RegisterDialog(this, true);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hanya admin yang dapat melakukan registrasi", "Forbidden", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_RegisterBuku

    private void makeOrder(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrder
        // TODO add your handling code here:
        if (currentUser instanceof Customer) {
            OrderDialog dialog = new OrderDialog(this, false);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hanya customer yang dapat melakukan pemesanan", "Forbidden", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_makeOrder

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllProduct;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextArea display;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
